[package]
name = "liquid-dsp-sys"
version = "0.1.0"
edition = "2021"

build = "build.rs"

crate-type = ["rlib"]

[dependencies]
num-complex = { version = "0.4.6", optional = true }

[build-dependencies]
bindgen = "0.70.1"

[features]
default = []
num_complex = ["num-complex"]
